"""Pydantic data models for the presentation pipeline."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

SlideType = Literal[
    "cover",
    "lead_in",
    "definition",
    "content",
    "history",
    "proof",
    "example",
    "exercise",
    "answer",
    "summary",
    "extension",
    "closing",
]


class SlideCard(BaseModel):
    """A card component within a slide — icon + title + body text."""

    icon: str = Field(description="Lucide icon name, e.g. 'triangle', 'book'")
    title: str
    body: str


class MaterialEntry(BaseModel):
    """A material asset in the library (background, illustration, or diagram)."""

    id: str
    type: Literal["background", "illustration", "diagram"]
    tags: list[str] = Field(default_factory=list)
    palette: str = ""
    source: Literal["programmatic", "ai_generated", "user_uploaded"] = "programmatic"
    description: str = ""
    resolution: tuple[int, int] = (1920, 1080)
    path: str = Field(description="Relative path within library directory")
    created_at: str = ""


class BackgroundAction(BaseModel):
    """LLM-specified background decision for a slide."""

    action: Literal["generate", "reuse"]
    style: str | None = Field(default=None, description="Pillow style for generate action")
    material_id: str | None = Field(default=None, description="Library ID for reuse action")
    tags: list[str] = Field(default_factory=list)


class ContentMaterial(BaseModel):
    """LLM-specified content material decision for a slide."""

    action: Literal["generate_diagram", "generate_illustration", "reuse"]
    position: Literal["full", "left", "right", "center"] = "center"
    material_id: str | None = None
    diagram_type: str | None = Field(default=None, description="flowchart|timeline|comparison|hierarchy|cycle")
    diagram_data: dict | None = None
    illustration_description: str | None = None
    illustration_style: str | None = None
    tags: list[str] = Field(default_factory=list)


class SlideContent(BaseModel):
    """Content specification for a single slide."""

    type: SlideType
    title: str
    subtitle: str | None = None
    cards: list[SlideCard] = Field(default_factory=list)
    formula: str | None = Field(
        default=None, description="Key formula displayed in footer area"
    )
    footer: str | None = Field(
        default=None, description="Footer text / summary line"
    )
    notes: str = Field(description="Speaker notes (teaching script)")
    content_blocks: list[dict] | None = Field(
        default=None, description="Additional structured content for complex slides"
    )
    bg_action: BackgroundAction | None = None
    content_materials: list[ContentMaterial] | None = None


class PresentationPlan(BaseModel):
    """Complete presentation plan generated by the LLM."""

    topic: str
    palette: str = Field(
        default="emerald", description="Color palette name from design system"
    )
    slides: list[SlideContent]
    language: str = "zh"
