"""Pydantic data models for the presentation pipeline."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

SlideType = Literal[
    "cover",
    "lead_in",
    "definition",
    "content",
    "history",
    "proof",
    "example",
    "exercise",
    "answer",
    "summary",
    "extension",
    "closing",
]


class SlideCard(BaseModel):
    """A card component within a slide — icon + title + body text."""

    icon: str = Field(description="Lucide icon name, e.g. 'triangle', 'book'")
    title: str
    body: str


class SlideContent(BaseModel):
    """Content specification for a single slide."""

    type: SlideType
    title: str
    subtitle: str | None = None
    cards: list[SlideCard] = Field(default_factory=list)
    formula: str | None = Field(
        default=None, description="Key formula displayed in footer area"
    )
    footer: str | None = Field(
        default=None, description="Footer text / summary line"
    )
    notes: str = Field(description="Speaker notes (teaching script)")
    content_blocks: list[dict] | None = Field(
        default=None, description="Additional structured content for complex slides"
    )


class PresentationPlan(BaseModel):
    """Complete presentation plan generated by the LLM."""

    topic: str
    palette: str = Field(
        default="emerald", description="Color palette name from design system"
    )
    slides: list[SlideContent]
    language: str = "zh"
